#!/usr/bin/env python

Import("env")

thirdparty_obj = []
thirdparty_dir = "#thirdparty/wgpu"

# Use WebGpu headers
env.Prepend(CPPPATH=[thirdparty_dir, thirdparty_dir + "/include"])

env.drivers_sources += thirdparty_obj

# Godot source files

driver_obj = []

env.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj

# Needed to force rebuilding the driver files when the thirdparty code is updated.
env.Depends(driver_obj, thirdparty_obj)

env.Prepend(LIBS=["wgpu_native"])
env.Prepend(LIBPATH=[thirdparty_dir])
