#!/usr/bin/env python

Import("env")

thirdparty_obj = []
thirdparty_dirs = ["#thirdparty/wgpu", "#thirdparty/naga-wrapper", "#thirdparty/naga-wrapper/target/debug/"]

# Use WebGpu headers
env.Prepend(CPPPATH=thirdparty_dirs)

# Godot source files

driver_obj = []

env.add_source_files(driver_obj, "*.cpp")
env.drivers_sources += driver_obj

# Needed to force rebuilding the driver files when the thirdparty code is updated.
env.Depends(driver_obj, thirdparty_obj)

env.Prepend(LIBS=["wgpu_native", "naga_wrapper"])
env.Prepend(LIBPATH=thirdparty_dirs)
